// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Actor details
type Actor struct {
	// Unique identifier for each actor
	ID string `json:"id"`
	// Full name of the actor
	FullName string `json:"fullName"`
	// Country in which the actor was born
	Country *string `json:"country"`
	// Gender of actor: Supported values are male or female
	Gender *string `json:"gender"`
}

// Director details
type Director struct {
	// Unique identifier for each director
	ID string `json:"id"`
	// Full name of the director
	FullName string `json:"fullName"`
	// Country in which the director was born
	Country *string `json:"country"`
}

// Director creation request
type DirectorRequest struct {
	// Full name of the director
	FullName string `json:"fullName"`
	// Country in which the director was born
	Country *string `json:"country"`
}

// Movie details
type Movie struct {
	// Unique identifier for each movie
	ID string `json:"id"`
	// Name of the movie
	Title string `json:"title"`
	// Year when the movie was released
	Year *int `json:"year"`
	// Genre for the movie, supported values should be: SciFi, Drama, Comedy or Action
	Genre *string `json:"genre"`
	// Budget for the movie, the value is provided in Euro
	Budget float64 `json:"budget"`
	// URL in which we can watch the trailer of this movie
	Trailer *string `json:"trailer"`
	// The director details of the movie
	Director *Director `json:"director"`
	// List of actors for the movie
	Actors []*Actor `json:"actors"`
}

// Request info for creating a movie
type MovieRequest struct {
	// Name of the movie
	Title string `json:"title"`
	// Year when the movie was released
	Year *int `json:"year"`
	// Genre for the movie, supported values should be: SciFi, Drama, Comedy or Action
	Genre *string `json:"genre"`
	// Budget for the movie, the value is provided in Euro
	Budget float64 `json:"budget"`
	// URL in which we can watch the trailer of this movie
	Trailer *string `json:"trailer"`
	// Identifier of director
	DirectorID string `json:"directorId"`
}
